version: "3.9"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: "defecthunterdb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "QWERTY"
    volumes:
      - postgres-data:/var/lib/postgresql/
    ports:
      - "5432:5432"
  rabbitmq:
    image: rabbitmq:3-management
    container_name: my-rabbit
    hostname: my-rabbit-host
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - "5672:5672"   # AMQP protocol port
      - "15672:15672" # Management UI port
    restart: unless-stopped

volumes:
  postgres-data: